import { z } from 'zod';

import {
  ApiErrorCode,
  FailureNature,
  ModerationErrorCode,
  ModerationVerdict,
  Service,
  Surface,
} from '@arthome/core';
import type { VocabularyIn } from '@arthome/core/schema';
import {
  InstantOut,
  int64,
  VOCABULARY_SOURCE_LOCAL,
  vocabularyIn,
  uuidIn,
} from '@arthome/core/schema';

import { StudioErrorEnvelopeSchema } from '../envelope/index.js';
import type {
  AccessorOf,
  Header,
  HeaderParameter,
  JsonResponse,
  PathParameter,
  QueryParameter,
  RouteBuilder,
} from '../http/index.js';
import { accessorOf, routeBuilder } from '../http/index.js';

const SURFACE: readonly [typeof Surface.STUDIO_WEB, typeof Surface.STUDIO_MOBILE] = [
  Surface.STUDIO_WEB,
  Surface.STUDIO_MOBILE,
];
const SORT_DIR = ['asc', 'desc'] as const;

const STUDIO_TAGS = [
  'bootstrap',
  'agenda',
  'publication',
  'ticketing',
  'run',
  'moderation',
  'crew',
  'payouts',
  'channel',
] as const;

/** The tags this document groups its operations by. */
export const StudioTag: AccessorOf<typeof STUDIO_TAGS> = accessorOf(STUDIO_TAGS);

export const TraceparentParameter: HeaderParameter<'traceparent', z.ZodString> = {
  name: 'traceparent',
  in: 'header',
  required: false,
  description:
    'W3C trace context, propagated down to the service and injected into the outbox **at write time**.',
  schema: z
    .string()
    .regex(new RegExp('^[0-9a-f]{2}-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$'))
    .meta({
      examples: ['00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01'],
    }),
};

export const SurfaceParameter: HeaderParameter<
  'X-Arthome-Surface',
  VocabularyIn<typeof SURFACE>,
  true
> = {
  name: 'X-Arthome-Surface',
  in: 'header',
  required: true,
  description:
    'The calling surface. The studio log **names names and places them**: "who decided, when, from\nwhich surface". A non-human actor — an automatic holding screen, a lease expiring — is an\nactor all the same, and carries `system`.\n',
  schema: vocabularyIn(SURFACE).meta({
    'x-arthome-vocabulary-source': 'SURFACES',
    'x-arthome-vocabulary-narrowing':
      'The two that may call the studio BFF. An input refuses where an output keeps an unknown value raw.',
    examples: ['studio-mobile'],
  }),
};

export const IdempotencyKeyParameter: HeaderParameter<'Idempotency-Key', z.ZodString, true> = {
  name: 'Idempotency-Key',
  in: 'header',
  required: true,
  description:
    "UUIDv7 generated by the surface **before sending**. The rule counts twice over here: a mobile\nnetwork replays, and a person who sees no answer presses twice. A replayed key returns the\noriginal response, verbatim. Lifetime 24 h. The other cases are `transport.md` §5.4's.\n",
  schema: uuidIn().meta({
    examples: ['019928f4-1b6c-7c3a-9f2e-6a1d0c4b8e77'],
  }),
};

export const IfRightsVersionParameter: HeaderParameter<'If-Rights-Version', z.ZodNumber> = {
  name: 'If-Rights-Version',
  in: 'header',
  required: false,
  description:
    '**The rights version the client holds**, symmetric to `X-Arthome-Rights-Version` in the\nresponse. Without it, the server cannot tell "you never had that right" from "you had it two\nhundred milliseconds ago": **two of the three refusal codes were out of reach**, and only\n`api.forbidden` was left — that is, the very indistinction the three codes existed to remove.\n\nThe difference, on duty, is not theoretical: on `api.forbidden` the application sends the\noperator back to the home screen as if they had never had the right; on\n`api.rights_version_stale` it reloads the bootstrap and **finds its place again**.\n\n**Which clock is authoritative**, since there were two: the server makes the client leave the\nreal-time rooms **immediately**, but a command still goes through for up to 60 s, the lifetime\nof the internal token. It is **the command that is authoritative** — a refusal is only\nrendered when the owning service renders it, on the loaded resource. The console may therefore\nfreeze before the writes stop, and that is the safe order: you stop showing before you stop\nacting.\n',
  schema: int64().meta({
    examples: [412],
  }),
};

export const ChannelIdParameter: PathParameter<'channelId', z.ZodString> = {
  name: 'channelId',
  in: 'path',
  required: true,
  schema: uuidIn().meta({
    examples: ['019928a0-7d31-7a10-b8c4-2f9e11a4c222'],
  }),
};

export const DateIdParameter: PathParameter<'dateId', z.ZodString> = {
  name: 'dateId',
  in: 'path',
  required: true,
  schema: uuidIn().meta({
    examples: ['019928a0-7d31-7a10-b8c4-2f9e11a4c001'],
  }),
};

export const PageParameter: QueryParameter<'page', z.ZodDefault<z.ZodInt>> = {
  name: 'page',
  in: 'query',
  required: false,
  description:
    '**Page number, from 1.** That is the affordance wanted: you pin a page and send it to a colleague.',
  schema: z.int().min(1).meta({ maximum: undefined }).default(1),
};

export const PageSizeParameter: QueryParameter<'pageSize', z.ZodDefault<z.ZodInt>> = {
  name: 'pageSize',
  in: 'query',
  required: false,
  description: 'Small pages, and deliberately so: a thumb does not scan a hundred rows.',
  schema: z.int().min(1).max(100).default(20),
};

export const SortByParameter: QueryParameter<'sortBy', z.ZodString> = {
  name: 'sortBy',
  in: 'query',
  required: false,
  description:
    "Sort key. **A key bearing on a field absent from this role's projection is refused** with\n`api.sort_key_forbidden`, never ignored.\n\nSorting by **state** follows the **state machine's canonical order**, not alphabetical order:\nit is domain data, served with the state (`orderRank`), and not a table each surface would\nreinvent.\n",
  schema: z.string().meta({
    examples: ['startsAt'],
  }),
};

export const SortDirParameter: QueryParameter<
  'sortDir',
  z.ZodDefault<VocabularyIn<typeof SORT_DIR>>
> = {
  name: 'sortDir',
  in: 'query',
  required: false,
  schema: vocabularyIn(SORT_DIR)
    .meta({
      'x-arthome-vocabulary-source': VOCABULARY_SOURCE_LOCAL,
      'x-arthome-vocabulary-reason':
        "A sort or filter key. It is a property of THIS endpoint's list — which orders it offers — not of the domain, and adding one is an endpoint change rather than a vocabulary change.",
    })
    .default('asc'),
};

export const CursorParameter: QueryParameter<'cursor', z.ZodString> = {
  name: 'cursor',
  in: 'query',
  required: false,
  description:
    '**The only two exceptions to "page + total"**: the moderation queue and the live chat.\nOpaque Base64 cursor on `(created_at, id)`, valid 24 h, `410 api.cursor_too_old` beyond.\n',
  schema: z.string(),
};

export const LimitParameter: QueryParameter<'limit', z.ZodDefault<z.ZodInt>> = {
  name: 'limit',
  in: 'query',
  required: false,
  schema: z.int().min(1).max(200).default(50),
};

export const ServedAtHeader: Header = {
  description:
    "The server instant of this response. Every duty countdown refers to it, never to the workstation's clock.",
  schema: InstantOut,
};

export const RightsVersionHeader: Header = {
  description:
    "**Carried on every response.** When it changes, the navigation is stale: the client reloads\nthe bootstrap. It is also pushed on the real-time channel, and the server makes the client\nleave a lost channel's rooms **without waiting for a reconnection**.\n",
  schema: int64(),
};

export const IdempotencyReplayedHeader: Header = {
  description: 'Present and `true` when the body is the memorised response of an earlier attempt.',
  schema: z.boolean(),
};

export const BadRequestResponse: JsonResponse<typeof StudioErrorEnvelopeSchema> = {
  description: 'Malformed request, or a mandatory filter missing.',
  content: {
    'application/json': {
      schema: StudioErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.PERIOD_FILTER_REQUIRED,
          nature: FailureNature.REFUSED,
          params: {
            maxRangeDays: 92,
          },
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const UnauthorizedResponse: JsonResponse<typeof StudioErrorEnvelopeSchema> = {
  description: 'Aucune session valide.',
  content: {
    'application/json': {
      schema: StudioErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.UNAUTHENTICATED,
          nature: FailureNature.REFUSED,
          params: {},
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const ForbiddenResponse: JsonResponse<typeof StudioErrorEnvelopeSchema> = {
  description:
    'Right absent, rights stale, access revoked, or channel left. Three distinct codes —\n`api.forbidden`, `api.rights_version_stale`, `CHANNEL_ACCESS_REVOKED` — because the person must know\nwhether to reload, to phone someone, or to give up.\n',
  content: {
    'application/json': {
      schema: StudioErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.RIGHTS_VERSION_STALE,
          nature: FailureNature.REFUSED,
          params: {
            currentRightsVersion: 412,
          },
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const NotFoundResponse: JsonResponse<typeof StudioErrorEnvelopeSchema> = {
  description: "Unknown resource, or outside this channel's perimeter.",
  content: {
    'application/json': {
      schema: StudioErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.NOT_FOUND,
          nature: FailureNature.REFUSED,
          params: {},
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const ConflictResponse: JsonResponse<typeof StudioErrorEnvelopeSchema> = {
  description:
    'A final business refusal, and the `code` says which. `state.conflict` carries **the current\nstate and version**; `publication.transition_irreversible` carries the transition attempted **and the\npromise committed**; `moderation.already_settled` carries **the winning verdict and its\nauthor**.\n',
  content: {
    'application/json': {
      schema: StudioErrorEnvelopeSchema,
      example: {
        error: {
          code: ModerationErrorCode.ALREADY_SETTLED,
          nature: FailureNature.REFUSED,
          params: {
            verdict: ModerationVerdict.REMOVE,
            settledBy: 'Claire D.',
            settledAt: '2026-09-21T20:30:58Z',
          },
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const GoneResponse: JsonResponse<typeof StudioErrorEnvelopeSchema> = {
  description: 'Resume cursor too old — a full reload is required, and the surface **knows** it.',
  content: {
    'application/json': {
      schema: StudioErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.CURSOR_TOO_OLD,
          nature: FailureNature.REFUSED,
          params: {
            maxAgeHours: 24,
          },
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const TooManyRequestsResponse: JsonResponse<typeof StudioErrorEnvelopeSchema> = {
  description: 'Rate limit reached.',
  content: {
    'application/json': {
      schema: StudioErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.RATE_LIMITED,
          nature: FailureNature.UNAVAILABLE,
          params: {
            retryAfterMs: 2000,
          },
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const UnavailableResponse: JsonResponse<typeof StudioErrorEnvelopeSchema> = {
  description:
    'Our servers. `nature: "unavailable"` lets someone on duty tell "retry" from "understand".',
  content: {
    'application/json': {
      schema: StudioErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.UPSTREAM_UNAVAILABLE,
          nature: FailureNature.UNAVAILABLE,
          params: {
            service: Service.STREAMING,
          },
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const studioV1: RouteBuilder<1, readonly [], Record<never, never>> = routeBuilder().version(
  1,
);
