import { z } from 'zod';

import {
  DatePane,
  DisplayState,
  PublicationChecklistItem,
  PublicationPromise,
  REPLAY_POLICIES,
  ReplayPolicy,
  Service,
} from '@arthome/core';
import type { VocabularyIn } from '@arthome/core/schema';
import { uuidOut, vocabularyIn } from '@arthome/core/schema';

import type { IdempotencyKeyParameter, IfRightsVersionParameter } from './components.js';
import {
  ChannelIdParameter,
  ConflictResponse,
  DateIdParameter,
  ForbiddenResponse,
  IdempotencyReplayedHeader,
  NotFoundResponse,
  StudioTag,
  SurfaceParameter,
  TraceparentParameter,
  operator,
  studioV1,
} from './components.js';
import { StudioEnvelopeMetaSchema } from '../envelope/index.js';
import type { JsonRequestBody, JsonResponse, Route, IdentifiedAccess } from '../http/index.js';
import { DateSheetSchema } from '../studio-stage/index.js';

const publicationRoutes = studioV1
  .identity(operator)
  .tags(StudioTag.PUBLICATION)
  .headers(SurfaceParameter, TraceparentParameter)
  .errors({ 403: ForbiddenResponse, 404: NotFoundResponse });
const channelDates = publicationRoutes
  .path('channels/{channelId}', ChannelIdParameter)
  .resource('dates', { id: DateIdParameter });

export const createDateDraft: Route<{
  method: 'post';
  version: 1;
  path: '/channels/{channelId}/dates';
  parameters: readonly [
    typeof ChannelIdParameter,
    typeof IdempotencyKeyParameter,
    typeof SurfaceParameter,
    typeof TraceparentParameter,
    typeof IfRightsVersionParameter,
  ];
  access: IdentifiedAccess<typeof operator, false>;
  requestBody: JsonRequestBody<
    z.ZodObject<
      {
        dateId: z.ZodString;
        showId: z.ZodString;
        venueId: z.ZodString;
        startsAt: z.ZodString;
        replayPolicy: VocabularyIn<typeof REPLAY_POLICIES>;
        replayWindowHours: z.ZodOptional<z.ZodNullable<z.ZodInt>>;
      },
      z.core.$strip
    >
  >;
  responses: {
    201: JsonResponse<
      z.ZodIntersection<
        typeof StudioEnvelopeMetaSchema,
        z.ZodObject<{ data: typeof DateSheetSchema }, z.core.$loose>
      >
    >;
    403: typeof ForbiddenResponse;
    409: typeof ConflictResponse;
  };
}> = channelDates.create({
  operationId: 'createDateDraft',
  summary: 'Creates a draft date — the identifier comes from the domain.',
  description:
    '**The identifier is generated by the domain (UUIDv7), not by a database default.** The first\nreason is here: the creation wizard announces "draft saved" **before any server round trip**,\nand a domain identifier lets you create, save locally and synchronise **without a correlation\nkey**. The other two reasons: the outbox requires the aggregate to know its identifier before\ninsertion, and time ordering fills the indexes properly.\n\n**The replay policy is chosen at creation**, because the public price depends on it. `none` is\n**final** for this date: you cannot later switch on a replay you promised not to make.\n',
  'x-arthome-maturity': 'stable',
  'x-arthome-upstream': [Service.CATALOG],
  item: DateSheetSchema,
  body: z.object({
    dateId: uuidOut().meta({
      description: '**Generated by the client** from `@arthome/core` (UUIDv7).',
    }),
    showId: uuidOut(),
    venueId: uuidOut(),
    startsAt: z
      .string()
      .regex(new RegExp('^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,3})?Z$'))
      .meta({
        format: 'date-time',
      }),
    replayPolicy: vocabularyIn(REPLAY_POLICIES).meta({
      'x-arthome-vocabulary-source': 'REPLAY_POLICIES',
    }),
    replayWindowHours: z
      .int()
      .meta({ minimum: undefined, maximum: undefined })
      .nullable()
      .optional(),
  }),
  example: {
    dateId: '019928c0-0000-7000-8000-000000000001',
    showId: '019928a0-7d31-7a10-b8c4-2f9e11a4c111',
    venueId: '019928a0-7d31-7a10-b8c4-2f9e11a4c444',
    startsAt: '2026-11-04T19:30:00Z',
    replayPolicy: ReplayPolicy.INCLUDED,
    replayWindowHours: 72,
  },
  responses: {
    201: {
      description: 'Draft created, with its publication and its checklist.',
      headers: {
        'Idempotency-Replayed': IdempotencyReplayedHeader,
      },
      content: {
        'application/json': {
          schema: z.intersection(
            StudioEnvelopeMetaSchema,
            z.looseObject({
              data: DateSheetSchema,
            }),
          ),
          example: {
            servedAt: '2026-09-21T18:02:00.000Z',
            rightsVersion: 412,
            data: {
              dateId: '019928c0-0000-7000-8000-000000000001',
              channelId: '019928a0-7d31-7a10-b8c4-2f9e11a4c222',
              title: 'Nuit blanche',
              startsAt: '2026-11-04T19:30:00Z',
              venueClock: {
                venueTimezone: 'Europe/Paris',
                venueUtcOffsetMin: 60,
              },
              runtimeMin: 95,
              openPanes: [
                DatePane.PUBLIC,
                DatePane.TICKETS,
                DatePane.CHAT,
                DatePane.TECH,
                DatePane.CREW,
                DatePane.REPLAY,
              ],
              publication: {
                dateId: '019928c0-0000-7000-8000-000000000001',
                state: DisplayState.DRAFT,
                orderRank: 1,
                version: 1,
                checklist: [
                  {
                    id: PublicationChecklistItem.TITLE_AND_DISCIPLINE,
                    satisfied: true,
                    source: Service.CATALOG,
                    blocking: true,
                  },
                  {
                    id: PublicationChecklistItem.POSTER,
                    satisfied: false,
                    source: Service.CATALOG,
                    blocking: true,
                  },
                  {
                    id: PublicationChecklistItem.AT_LEAST_ONE_ACTIVE_PRICE,
                    satisfied: false,
                    source: Service.TICKETING,
                    blocking: true,
                  },
                  {
                    id: PublicationChecklistItem.TECHNICAL_CHECK_PASSED,
                    satisfied: false,
                    source: Service.STREAMING,
                    blocking: true,
                  },
                  {
                    id: PublicationChecklistItem.CHAPTERS_PLANNED,
                    satisfied: false,
                    source: Service.CATALOG,
                    blocking: false,
                  },
                ],
                offeredTransitions: [
                  {
                    from: DisplayState.DRAFT,
                    to: DisplayState.RESERVE,
                    irreversible: false,
                  },
                  {
                    from: DisplayState.DRAFT,
                    to: DisplayState.SCHEDULED,
                    irreversible: true,
                    promiseCode: PublicationPromise.PRICES_ENGAGED,
                  },
                ],
              },
            },
          },
        },
      },
    },
    403: ForbiddenResponse,
    409: ConflictResponse,
  },
});
