import { z } from 'zod';

import {
  AudienceSanction,
  BLACKOUT_REASONS,
  CatalogErrorCode,
  DATE_OUTCOMES,
  DateOutcome,
  DatePane,
  DisplayState,
  DomainErrorCode,
  FailureNature,
  Locale,
  MemberRole,
  PUBLICATION_PROMISES,
  PublicationChecklistItem,
  PublicationPromise,
  PublicationState,
  REPLAY_POLICIES,
  ReplayPolicy,
  RIGHTS_SCOPES,
  RightsScope,
  Service,
} from '@arthome/core';
import type { VocabularyIn, VocabularyOut, VocabularyOutNullable } from '@arthome/core/schema';
import {
  InstantOut,
  MoneyOut,
  uuidOut,
  vocabularyIn,
  vocabularyOut,
  vocabularyOutNullable,
} from '@arthome/core/schema';

import type { IdempotencyKeyParameter, IfRightsVersionParameter } from './components.js';
import {
  ChannelIdParameter,
  ConflictResponse,
  DateIdParameter,
  ForbiddenResponse,
  IdempotencyReplayedHeader,
  NotFoundResponse,
  RightsVersionHeader,
  StudioTag,
  SurfaceParameter,
  TraceparentParameter,
  operator,
  studioV1,
} from './components.js';
import { StudioEnvelopeMetaSchema, StudioErrorEnvelopeSchema } from '../envelope/index.js';
import type {
  JsonRequestBody,
  JsonResponse,
  Route,
  IdentifiedAccess,
  ExpectedVersionQuery,
} from '../http/index.js';
import { DateSheetSchema, PublicationSchema } from '../studio-stage/index.js';
import { StudioLocalizedTextSchema } from '../text/index.js';

const publicationRoutes = studioV1
  .identity(operator)
  .tags(StudioTag.PUBLICATION)
  .headers(SurfaceParameter, TraceparentParameter)
  .errors({ 403: ForbiddenResponse, 404: NotFoundResponse });
const date = publicationRoutes.resource('dates', { id: DateIdParameter });
const channelDates = publicationRoutes
  .path('channels/{channelId}', ChannelIdParameter)
  .resource('dates', { id: DateIdParameter });

const MOVE_DATE_PUBLICATION_STATE_TO: readonly [
  typeof PublicationState.DRAFT,
  typeof PublicationState.RESERVE,
  typeof PublicationState.SCHEDULED,
  typeof PublicationState.TECHNICAL,
  typeof PublicationState.REPLAY_ONLINE,
] = [
  PublicationState.DRAFT,
  PublicationState.RESERVE,
  PublicationState.SCHEDULED,
  PublicationState.TECHNICAL,
  PublicationState.REPLAY_ONLINE,
];

export const createDateDraft: Route<{
  method: 'post';
  version: 1;
  path: '/channels/{channelId}/dates';
  parameters: readonly [
    typeof ChannelIdParameter,
    typeof IdempotencyKeyParameter,
    typeof SurfaceParameter,
    typeof TraceparentParameter,
    typeof IfRightsVersionParameter,
  ];
  access: IdentifiedAccess<typeof operator, false>;
  requestBody: JsonRequestBody<
    z.ZodObject<
      {
        dateId: z.ZodString;
        showId: z.ZodString;
        venueId: z.ZodString;
        startsAt: z.ZodString;
        replayPolicy: VocabularyIn<typeof REPLAY_POLICIES>;
        replayWindowHours: z.ZodOptional<z.ZodNullable<z.ZodInt>>;
      },
      z.core.$strip
    >
  >;
  responses: {
    201: JsonResponse<
      z.ZodIntersection<
        typeof StudioEnvelopeMetaSchema,
        z.ZodObject<{ data: typeof DateSheetSchema }, z.core.$loose>
      >
    >;
    403: typeof ForbiddenResponse;
    409: typeof ConflictResponse;
  };
}> = channelDates.create({
  operationId: 'createDateDraft',
  summary: 'Creates a draft date — the identifier comes from the domain.',
  description:
    '**The identifier is generated by the domain (UUIDv7), not by a database default.** The first\nreason is here: the creation wizard announces "draft saved" **before any server round trip**,\nand a domain identifier lets you create, save locally and synchronise **without a correlation\nkey**. The other two reasons: the outbox requires the aggregate to know its identifier before\ninsertion, and time ordering fills the indexes properly.\n\n**The replay policy is chosen at creation**, because the public price depends on it. `none` is\n**final** for this date: you cannot later switch on a replay you promised not to make.\n',
  'x-arthome-maturity': 'stable',
  'x-arthome-upstream': [Service.CATALOG],
  item: DateSheetSchema,
  body: z.object({
    dateId: uuidOut().meta({
      description: '**Generated by the client** from `@arthome/core` (UUIDv7).',
    }),
    showId: uuidOut(),
    venueId: uuidOut(),
    startsAt: z
      .string()
      .regex(new RegExp('^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,3})?Z$'))
      .meta({
        format: 'date-time',
      }),
    replayPolicy: vocabularyIn(REPLAY_POLICIES).meta({
      'x-arthome-vocabulary-source': 'REPLAY_POLICIES',
    }),
    replayWindowHours: z
      .int()
      .meta({ minimum: undefined, maximum: undefined })
      .nullable()
      .optional(),
  }),
  example: {
    dateId: '019928c0-0000-7000-8000-000000000001',
    showId: '019928a0-7d31-7a10-b8c4-2f9e11a4c111',
    venueId: '019928a0-7d31-7a10-b8c4-2f9e11a4c444',
    startsAt: '2026-11-04T19:30:00Z',
    replayPolicy: ReplayPolicy.INCLUDED,
    replayWindowHours: 72,
  },
  responses: {
    201: {
      description: 'Draft created, with its publication and its checklist.',
      headers: {
        'Idempotency-Replayed': IdempotencyReplayedHeader,
      },
      content: {
        'application/json': {
          schema: z.intersection(
            StudioEnvelopeMetaSchema,
            z.looseObject({
              data: DateSheetSchema,
            }),
          ),
          example: {
            servedAt: '2026-09-21T18:02:00.000Z',
            rightsVersion: 412,
            data: {
              dateId: '019928c0-0000-7000-8000-000000000001',
              channelId: '019928a0-7d31-7a10-b8c4-2f9e11a4c222',
              title: 'Nuit blanche',
              startsAt: '2026-11-04T19:30:00Z',
              venueClock: {
                venueTimezone: 'Europe/Paris',
                venueUtcOffsetMin: 60,
              },
              runtimeMin: 95,
              openPanes: [
                DatePane.PUBLIC,
                DatePane.TICKETS,
                DatePane.CHAT,
                DatePane.TECH,
                DatePane.CREW,
                DatePane.REPLAY,
              ],
              publication: {
                dateId: '019928c0-0000-7000-8000-000000000001',
                state: DisplayState.DRAFT,
                orderRank: 1,
                version: 1,
                checklist: [
                  {
                    id: PublicationChecklistItem.TITLE_AND_DISCIPLINE,
                    satisfied: true,
                    source: Service.CATALOG,
                    blocking: true,
                  },
                  {
                    id: PublicationChecklistItem.POSTER,
                    satisfied: false,
                    source: Service.CATALOG,
                    blocking: true,
                  },
                  {
                    id: PublicationChecklistItem.AT_LEAST_ONE_ACTIVE_PRICE,
                    satisfied: false,
                    source: Service.TICKETING,
                    blocking: true,
                  },
                  {
                    id: PublicationChecklistItem.TECHNICAL_CHECK_PASSED,
                    satisfied: false,
                    source: Service.STREAMING,
                    blocking: true,
                  },
                  {
                    id: PublicationChecklistItem.CHAPTERS_PLANNED,
                    satisfied: false,
                    source: Service.CATALOG,
                    blocking: false,
                  },
                ],
                offeredTransitions: [
                  {
                    from: DisplayState.DRAFT,
                    to: DisplayState.RESERVE,
                    irreversible: false,
                  },
                  {
                    from: DisplayState.DRAFT,
                    to: DisplayState.SCHEDULED,
                    irreversible: true,
                    promiseCode: PublicationPromise.PRICES_ENGAGED,
                  },
                ],
              },
            },
          },
        },
      },
    },
    403: ForbiddenResponse,
    409: ConflictResponse,
  },
});

export const getDateSheet: Route<{
  method: 'get';
  version: 1;
  path: '/dates/{dateId}/sheet';
  parameters: readonly [
    typeof DateIdParameter,
    typeof SurfaceParameter,
    typeof TraceparentParameter,
  ];
  access: IdentifiedAccess<typeof operator, false>;
  responses: {
    200: JsonResponse<
      z.ZodIntersection<
        typeof StudioEnvelopeMetaSchema,
        z.ZodObject<{ data: typeof DateSheetSchema }, z.core.$loose>
      >
    >;
    403: typeof ForbiddenResponse;
    404: typeof NotFoundResponse;
  };
}> = date.single('sheet').find({
  operationId: 'getDateSheet',
  item: DateSheetSchema,
  summary: "A date's record, and the list of panes open to this person.",
  description:
    '**One call for the record, then one call per open pane, at its owner.** A moderator must be\nable to load the `chat` pane **without** loading the whole record, otherwise ticketing travels\nfor nothing.\n\n`openPanes` is **served**, not inferred: the very layout of the screen depends on the\neffective rights, and the overview appears only beyond three open panes.\n',
  'x-arthome-maturity': 'stable',
  'x-arthome-upstream': [Service.CATALOG],
  responses: {
    200: {
      description: 'The record and its publication.',
      headers: {
        'X-Arthome-Rights-Version': RightsVersionHeader,
      },
      content: {
        'application/json': {
          schema: z.intersection(
            StudioEnvelopeMetaSchema,
            z.looseObject({
              data: DateSheetSchema,
            }),
          ),
          example: {
            servedAt: '2026-09-21T18:03:00.000Z',
            rightsVersion: 412,
            data: {
              dateId: '019928a0-7d31-7a10-b8c4-2f9e11a4c001',
              channelId: '019928a0-7d31-7a10-b8c4-2f9e11a4c222',
              title: 'Nuit blanche',
              startsAt: '2026-09-21T19:00:00Z',
              venueClock: {
                venueTimezone: 'Europe/Paris',
                venueUtcOffsetMin: 120,
              },
              runtimeMin: 95,
              openPanes: [DatePane.PUBLIC, DatePane.TICKETS, DatePane.TECH],
              publication: {
                dateId: '019928a0-7d31-7a10-b8c4-2f9e11a4c001',
                state: DisplayState.SCHEDULED,
                orderRank: 3,
                version: 7,
                checklist: [],
                offeredTransitions: [],
              },
            },
          },
        },
      },
    },
  },
});

export const getDatePublicPane: Route<{
  method: 'get';
  version: 1;
  path: '/dates/{dateId}/panes/public';
  parameters: readonly [
    typeof DateIdParameter,
    typeof SurfaceParameter,
    typeof TraceparentParameter,
  ];
  access: IdentifiedAccess<typeof operator, false>;
  responses: {
    200: JsonResponse<
      z.ZodIntersection<
        typeof StudioEnvelopeMetaSchema,
        z.ZodObject<
          {
            data: z.ZodObject<
              {
                title: z.ZodOptional<z.ZodString>;
                categoryId: z.ZodOptional<z.ZodString>;
                genreIds: z.ZodOptional<z.ZodArray<z.ZodString>>;
                tagIds: z.ZodOptional<z.ZodArray<z.ZodString>>;
                synopsis: z.ZodOptional<typeof StudioLocalizedTextSchema>;
                slug: z.ZodOptional<z.ZodString>;
                canonicalUrl: z.ZodOptional<z.ZodString>;
                rights: z.ZodOptional<
                  z.ZodObject<
                    {
                      scope: z.ZodOptional<VocabularyOut>;
                      blackoutCountries: z.ZodOptional<z.ZodArray<z.ZodString>>;
                      blackoutReasonCode: z.ZodOptional<VocabularyOutNullable>;
                    },
                    z.core.$loose
                  >
                >;
                version: z.ZodOptional<z.ZodInt>;
              },
              z.core.$loose
            >;
          },
          z.core.$loose
        >
      >
    >;
    403: typeof ForbiddenResponse;
    404: typeof NotFoundResponse;
  };
}> = date.path('panes').defineRoute({
  method: 'get',
  path: '/public',
  operationId: 'getDatePublicPane',
  summary: "A date's public pane — what is published.",
  description:
    'One of the five panes that were missing. The motive "one call for the record, then one call\nper open pane, **at its owner**" was stated twice and implemented once: a `moderation` role\nreceived `openPanes: [chat]` and had **no pane to call**, a `coordination` role received\n`[tech, crew]` — neither of the two existed.\n\nOpen to `artist` and `production`.\n',
  'x-arthome-maturity': 'stable',
  'x-arthome-upstream': [Service.CATALOG],
  responses: {
    200: {
      description: 'The public pane.',
      content: {
        'application/json': {
          schema: z.intersection(
            StudioEnvelopeMetaSchema,
            z.looseObject({
              data: z.looseObject({
                title: z.string().optional(),
                categoryId: z.string().optional(),
                genreIds: z.array(z.string()).optional(),
                tagIds: z.array(z.string()).optional(),
                synopsis: StudioLocalizedTextSchema.optional(),
                slug: z.string().optional(),
                canonicalUrl: z
                  .string()
                  .meta({
                    format: 'uri',
                  })
                  .optional(),
                rights: z
                  .looseObject({
                    scope: vocabularyOut(RIGHTS_SCOPES).optional(),
                    blackoutCountries: z
                      .array(z.string().regex(new RegExp('^[A-Z]{2}$')))
                      .optional(),
                    blackoutReasonCode: vocabularyOutNullable(BLACKOUT_REASONS).optional(),
                  })
                  .optional(),
                version: z.int().meta({ minimum: undefined, maximum: undefined }).optional(),
              }),
            }),
          ),
          example: {
            servedAt: '2026-09-21T18:03:25.000Z',
            rightsVersion: 412,
            data: {
              title: 'Nuit blanche',
              categoryId: 'dance-contemporary',
              genreIds: ['dance-contemporary-repertoire'],
              slug: '2026-09-21',
              canonicalUrl: 'https://arthome.fr/show/nuit-blanche/date/2026-09-21',
              rights: {
                scope: RightsScope.WORLDWIDE,
                blackoutCountries: [],
              },
              version: 8,
            },
          },
        },
      },
    },
  },
});

export const getDateReplayPane: Route<{
  method: 'get';
  version: 1;
  path: '/dates/{dateId}/panes/replay';
  parameters: readonly [
    typeof DateIdParameter,
    typeof SurfaceParameter,
    typeof TraceparentParameter,
  ];
  access: IdentifiedAccess<typeof operator, false>;
  responses: {
    200: JsonResponse<
      z.ZodIntersection<
        typeof StudioEnvelopeMetaSchema,
        z.ZodObject<
          {
            data: z.ZodObject<
              {
                policy: z.ZodOptional<VocabularyOut>;
                windowHours: z.ZodOptional<z.ZodNullable<z.ZodInt>>;
                assetReady: z.ZodOptional<z.ZodBoolean>;
                durationSec: z.ZodOptional<z.ZodNullable<z.ZodInt>>;
                availableFrom: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                expiresAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
                unitPrice: z.ZodOptional<typeof MoneyOut>;
                views: z.ZodOptional<z.ZodNullable<z.ZodInt>>;
                revenue: z.ZodOptional<typeof MoneyOut>;
                version: z.ZodOptional<z.ZodInt>;
              },
              z.core.$loose
            >;
          },
          z.core.$loose
        >
      >
    >;
    403: typeof ForbiddenResponse;
    404: typeof NotFoundResponse;
  };
}> = date.path('panes').defineRoute({
  method: 'get',
  path: '/replay',
  operationId: 'getDateReplayPane',
  summary: "A date's replay pane — the promise, the file, the sale.",
  description:
    'The three things the sources conflated, served separately: the **promise** belongs to\n`catalog`, the **file and its expiry** to `streaming`, the **sale** to `ticketing`.\n\nOpen to `artist` and `production`.\n',
  'x-arthome-maturity': 'provisional',
  'x-arthome-upstream': [Service.CATALOG, Service.STREAMING, Service.TICKETING],
  responses: {
    200: {
      description: 'Policy, active, remaining window, sale, audience.',
      content: {
        'application/json': {
          schema: z.intersection(
            StudioEnvelopeMetaSchema,
            z.looseObject({
              data: z.looseObject({
                policy: vocabularyOut(REPLAY_POLICIES).optional(),
                windowHours: z
                  .int()
                  .meta({ minimum: undefined, maximum: undefined })
                  .nullable()
                  .optional(),
                assetReady: z.boolean().optional(),
                durationSec: z
                  .int()
                  .meta({ minimum: undefined, maximum: undefined })
                  .nullable()
                  .optional(),
                availableFrom: InstantOut.nullable().optional(),
                expiresAt: InstantOut.nullable()
                  .meta({
                    description:
                      '**Derived** from the end of the live show and the served window, never set by hand.',
                  })
                  .optional(),
                unitPrice: MoneyOut.meta({
                  'x-arthome-tax-basis': 'inclusive',
                }).optional(),
                views: z
                  .int()
                  .meta({ minimum: undefined, maximum: undefined })
                  .nullable()
                  .optional(),
                revenue: MoneyOut.meta({
                  'x-arthome-tax-basis': 'inclusive',
                  description: '**Absent** without `canRevenue`.',
                }).optional(),
                version: z.int().meta({ minimum: undefined, maximum: undefined }).optional(),
              }),
            }),
          ),
          example: {
            servedAt: '2026-09-22T10:00:20.000Z',
            rightsVersion: 412,
            data: {
              policy: ReplayPolicy.INCLUDED,
              windowHours: 72,
              assetReady: true,
              durationSec: 5700,
              availableFrom: '2026-09-21T22:00:00Z',
              expiresAt: '2026-09-24T22:00:00Z',
              views: 412,
              version: 2,
            },
          },
        },
      },
    },
  },
});

export const moveDatePublicationState: Route<{
  method: 'post';
  version: 1;
  path: '/dates/{dateId}/publication/transitions';
  parameters: readonly [
    typeof DateIdParameter,
    typeof IdempotencyKeyParameter,
    typeof SurfaceParameter,
    typeof TraceparentParameter,
    typeof IfRightsVersionParameter,
  ];
  access: IdentifiedAccess<typeof operator, false>;
  requestBody: JsonRequestBody<
    z.ZodObject<
      {
        to: VocabularyIn<typeof MOVE_DATE_PUBLICATION_STATE_TO>;
        expectedVersion: z.ZodInt;
        acknowledgedPromiseCode: z.ZodOptional<
          z.ZodLiteral<(typeof PUBLICATION_PROMISES)[number] | null>
        >;
      },
      z.core.$strip
    >
  >;
  responses: {
    200: JsonResponse<
      z.ZodIntersection<
        typeof StudioEnvelopeMetaSchema,
        z.ZodObject<{ data: typeof PublicationSchema }, z.core.$loose>
      >
    >;
    403: typeof ForbiddenResponse;
    409: JsonResponse<typeof StudioErrorEnvelopeSchema>;
  };
}> = date.action('publication/transitions', {
  operationId: 'moveDatePublicationState',
  summary: 'Moves the date through the state machine.',
  description:
    '**Three guarantees, and not one of them is an interface courtesy.**\n\n1. **The server refuses the reverse transition.** Not offering it in the interface is not a\n   guarantee. The refusal carries `publication.transition_irreversible`, the transition attempted **and\n   the promise committed** as parameters — `prices_engaged` for `draft|reserve → scheduled`,\n   `replay_sold` for `ended → replay_online`. **The lock bears on the `from > to` pair, not\n   on the state.**\n2. **It is conditional and versioned.** Two people can be on the record: a command sent from\n   `technical` while the current state is `live` is refused with `state.conflict`,\n   **with the current state and version**. The studio is multi-operator without a lock; the arbitration\n   is on the server.\n3. **`Idempotency-Key` is mandatory, not recommended**: the transition commits a public price\n   or a sale.\n\n**The publication gate is served, not recomputed**: the refusal names the **missing** items as\nparameters, since the screen counts them ("publish — 3 missing"). Never a percentage, which\nthe client would compute.\n\n**The attempt to go backwards is itself logged**: an attempt to walk back a committed price is\nin itself a piece of operational information.\n\nTwo transitions are **not** commands: `technical → live` and `live → ended` are **caused by a\n`streaming` event**. Publication does not command the broadcast, it **learns** of it — only\n`streaming` knows whether the feed is arriving.\n',
  'x-arthome-maturity': 'stable',
  'x-arthome-upstream': [Service.CATALOG],
  body: z.object({
    to: vocabularyIn(MOVE_DATE_PUBLICATION_STATE_TO).meta({
      'x-arthome-vocabulary-source': 'PUBLICATION_STATES',
      'x-arthome-vocabulary-narrowing':
        '`live` and `ended` are not commands: they are caused by a streaming event, because only streaming knows whether the feed is arriving. Offering them would let a studio declare a date on air that is sending nothing.',
      description:
        "**A strict narrowing of `PUBLICATION_STATES`, and the two missing members carry the\ndocument's most important rule about this path.** `live` and `ended` are **not\ncommands**: they are caused by a `streaming` event, because only `streaming` knows\nwhether the feed is arriving. Publication does not command the broadcast, it learns\nof it. Offering them here would let a studio declare a date on air that is sending\nnothing.\n",
    }),
    expectedVersion: z.int().meta({ minimum: undefined, maximum: undefined }),
    acknowledgedPromiseCode: z
      .literal([...PUBLICATION_PROMISES, null])
      .meta({
        type: ['string', 'null'],
        'x-arthome-vocabulary-source': 'PUBLICATION_PROMISES',
        description:
          "**Mandatory for a transition with no way back.** The confirmation carries the promise's\ncode, and its wording comes from the contract: the interface does not invent it.\nMissing or different, the transition is refused with `publication.promise_unacknowledged`\nand the promise to confirm.\n",
      })
      .optional(),
  }),
  example: {
    to: DisplayState.SCHEDULED,
    expectedVersion: 7,
    acknowledgedPromiseCode: PublicationPromise.PRICES_ENGAGED,
  },
  responses: {
    200: {
      description:
        'Transition applied. The publication up to date, with its newly offered transitions.',
      headers: {
        'Idempotency-Replayed': IdempotencyReplayedHeader,
      },
      content: {
        'application/json': {
          schema: z.intersection(
            StudioEnvelopeMetaSchema,
            z.looseObject({
              data: PublicationSchema,
            }),
          ),
          example: {
            servedAt: '2026-09-21T18:04:00.000Z',
            rightsVersion: 412,
            data: {
              dateId: '019928a0-7d31-7a10-b8c4-2f9e11a4c001',
              state: DisplayState.SCHEDULED,
              orderRank: 3,
              version: 8,
              publishedAt: '2026-09-21T18:04:00Z',
              pricesLockedAt: '2026-09-21T18:04:00Z',
              checklist: [],
              offeredTransitions: [
                {
                  from: DisplayState.SCHEDULED,
                  to: DisplayState.TECHNICAL,
                  irreversible: false,
                },
              ],
            },
          },
        },
      },
    },
    403: ForbiddenResponse,
    409: {
      description:
        '`state.conflict` (with the current state and version),\n`publication.transition_irreversible` (with the promise committed),\n`publication.promise_unacknowledged` (a one-way transition sent without its promise), or\n`publication.checklist_incomplete` (with the list of what is missing).\n',
      content: {
        'application/json': {
          schema: StudioErrorEnvelopeSchema,
          example: {
            error: {
              code: DomainErrorCode.PUBLICATION_CHECKLIST_INCOMPLETE,
              nature: FailureNature.REFUSED,
              params: {
                missing: [
                  PublicationChecklistItem.POSTER,
                  PublicationChecklistItem.AT_LEAST_ONE_ACTIVE_PRICE,
                  PublicationChecklistItem.TECHNICAL_CHECK_PASSED,
                ],
              },
              traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
            },
            servedAt: '2026-09-21T18:04:00.000Z',
          },
        },
      },
    },
  },
});

export const setDateReplayPolicy: Route<{
  method: 'put';
  version: 1;
  path: '/dates/{dateId}/replay-policy';
  parameters: readonly [
    typeof DateIdParameter,
    typeof IdempotencyKeyParameter,
    typeof SurfaceParameter,
    typeof TraceparentParameter,
    typeof IfRightsVersionParameter,
  ];
  access: IdentifiedAccess<typeof operator, false>;
  requestBody: JsonRequestBody<
    z.ZodObject<
      {
        policy: VocabularyIn<typeof REPLAY_POLICIES>;
        windowHours: z.ZodOptional<z.ZodNullable<z.ZodInt>>;
        expectedVersion: z.ZodInt;
      },
      z.core.$strip
    >
  >;
  responses: {
    200: JsonResponse<
      z.ZodIntersection<
        typeof StudioEnvelopeMetaSchema,
        z.ZodObject<{ data: typeof PublicationSchema }, z.core.$loose>
      >
    >;
    409: JsonResponse<typeof StudioErrorEnvelopeSchema>;
  };
}> = date.single('replay-policy').replace({
  operationId: 'setDateReplayPolicy',
  item: PublicationSchema,
  summary: 'Sets the replay policy — the promise made before the purchase.',
  description:
    '**`none` is final for this date.** You cannot later switch on a replay you promised not to\nmake: the public price depended on it. The other values lock when ticketing opens.\n\nThe contract separates three things the sources conflated: the **promise** belongs to\n`catalog`, the **sale** to `ticketing`, the **file and its expiry** to `streaming`.\n',
  'x-arthome-maturity': 'stable',
  'x-arthome-upstream': [Service.CATALOG],
  body: z.object({
    policy: vocabularyIn(REPLAY_POLICIES).meta({
      'x-arthome-vocabulary-source': 'REPLAY_POLICIES',
    }),
    windowHours: z.int().min(1).meta({ maximum: undefined }).nullable().optional(),
    expectedVersion: z.int().meta({ minimum: undefined, maximum: undefined }),
  }),
  example: {
    policy: ReplayPolicy.UNIT,
    windowHours: 72,
    expectedVersion: 7,
  },
  responses: {
    200: {
      description: 'Policy up to date.',
      content: {
        'application/json': {
          schema: z.intersection(
            StudioEnvelopeMetaSchema,
            z.looseObject({
              data: PublicationSchema,
            }),
          ),
          example: {
            servedAt: '2026-09-21T18:08:00.000Z',
            rightsVersion: 412,
            data: {
              dateId: '019928a0-7d31-7a10-b8c4-2f9e11a4c001',
              state: DisplayState.SCHEDULED,
              orderRank: 3,
              version: 8,
              checklist: [],
              offeredTransitions: [],
            },
          },
        },
      },
    },
    409: {
      description: '`date.replay_policy_final` when the policy was `none`.',
      content: {
        'application/json': {
          schema: StudioErrorEnvelopeSchema,
          example: {
            error: {
              code: CatalogErrorCode.REPLAY_POLICY_FINAL,
              nature: FailureNature.REFUSED,
              params: {
                currentPolicy: AudienceSanction.NONE,
              },
              traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
            },
            servedAt: '2026-09-21T18:08:00.000Z',
          },
        },
      },
    },
  },
});

export const deleteDate: Route<{
  method: 'delete';
  version: 1;
  path: '/dates/{dateId}';
  parameters: readonly [
    typeof DateIdParameter,
    typeof IdempotencyKeyParameter,
    ExpectedVersionQuery,
    typeof SurfaceParameter,
    typeof TraceparentParameter,
    typeof IfRightsVersionParameter,
  ];
  access: IdentifiedAccess<typeof operator, false>;
  responses: {
    200: JsonResponse<
      z.ZodIntersection<
        typeof StudioEnvelopeMetaSchema,
        z.ZodObject<
          {
            data: z.ZodOptional<
              z.ZodObject<{ deleted: z.ZodOptional<z.ZodBoolean> }, z.core.$loose>
            >;
          },
          z.core.$loose
        >
      >
    >;
    409: JsonResponse<typeof StudioErrorEnvelopeSchema>;
    404: typeof NotFoundResponse;
  };
}> = date.delete({
  operationId: 'deleteDate',
  response: z.looseObject({ deleted: z.boolean().optional() }).optional(),
  summary: 'Deletes a date.',
  description:
    '**Refused if seats remain sold**, and the refusal carries **the count** as a parameter: the\nscreen must say "174 seats sold", not "not possible". It is a domain rule, not an interface\nguard, and the application must not try to check it on its own.\n',
  'x-arthome-maturity': 'stable',
  'x-arthome-upstream': [Service.CATALOG],
  responses: {
    200: {
      description: 'Date deleted.',
      content: {
        'application/json': {
          schema: z.intersection(
            StudioEnvelopeMetaSchema,
            z.looseObject({
              data: z
                .looseObject({
                  deleted: z.boolean().optional(),
                })
                .optional(),
            }),
          ),
          example: {
            servedAt: '2026-09-21T18:09:00.000Z',
            rightsVersion: 412,
            data: {
              deleted: true,
            },
          },
        },
      },
    },
    409: {
      description: '`date.has_sold_seats`, with the count.',
      content: {
        'application/json': {
          schema: StudioErrorEnvelopeSchema,
          example: {
            error: {
              code: CatalogErrorCode.DATE_HAS_SOLD_SEATS,
              nature: FailureNature.REFUSED,
              params: {
                seatsSold: 174,
              },
              traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
            },
            servedAt: '2026-09-21T18:09:00.000Z',
          },
        },
      },
    },
    404: NotFoundResponse,
  },
});

export const duplicateDate: Route<{
  method: 'post';
  version: 1;
  path: '/dates/{dateId}/duplicate';
  parameters: readonly [
    typeof DateIdParameter,
    typeof IdempotencyKeyParameter,
    typeof SurfaceParameter,
    typeof TraceparentParameter,
    typeof IfRightsVersionParameter,
  ];
  access: IdentifiedAccess<typeof operator, false>;
  requestBody: JsonRequestBody<
    z.ZodObject<
      {
        newDateId: z.ZodString;
        startsAt: z.ZodString;
        applyToSeries: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
      },
      z.core.$strip
    >
  >;
  responses: {
    201: JsonResponse<
      z.ZodIntersection<
        typeof StudioEnvelopeMetaSchema,
        z.ZodObject<{ data: typeof DateSheetSchema }, z.core.$loose>
      >
    >;
    409: typeof ConflictResponse;
  };
}> = date.action('duplicate', {
  operationId: 'duplicateDate',
  summary: 'Duplicates a date, or applies it to the series.',
  description:
    '**"Apply to the series" excludes prices and capacity** — never carried over, because each\ndate commits its own buyers. The contract says so rather than leaving the interface to guess\nit.\n',
  'x-arthome-maturity': 'stable',
  'x-arthome-upstream': [Service.CATALOG],
  body: z.object({
    newDateId: uuidOut().meta({
      description: 'Generated client-side by the domain.',
    }),
    startsAt: z
      .string()
      .regex(new RegExp('^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,3})?Z$'))
      .meta({
        format: 'date-time',
      }),
    applyToSeries: z.boolean().default(false).optional(),
  }),
  example: {
    newDateId: '019928c1-0000-7000-8000-000000000001',
    startsAt: '2026-11-05T19:30:00Z',
  },
  responses: {
    201: {
      description: "New date created, **without** the original's prices or capacity.",
      content: {
        'application/json': {
          schema: z.intersection(
            StudioEnvelopeMetaSchema,
            z.looseObject({
              data: DateSheetSchema,
            }),
          ),
          example: {
            servedAt: '2026-09-21T18:10:00.000Z',
            rightsVersion: 412,
            data: {
              dateId: '019928c1-0000-7000-8000-000000000001',
              channelId: '019928a0-7d31-7a10-b8c4-2f9e11a4c222',
              title: 'Nuit blanche',
              startsAt: '2026-11-05T19:30:00Z',
              openPanes: [DatePane.PUBLIC, DatePane.TICKETS],
              publication: {
                dateId: '019928c1-0000-7000-8000-000000000001',
                state: DisplayState.DRAFT,
                orderRank: 1,
                version: 1,
                checklist: [],
                offeredTransitions: [],
              },
            },
          },
        },
      },
    },
    409: ConflictResponse,
  },
});

export const decideDateOutcome: Route<{
  method: 'post';
  version: 1;
  path: '/dates/{dateId}/outcome';
  parameters: readonly [
    typeof DateIdParameter,
    typeof IdempotencyKeyParameter,
    typeof SurfaceParameter,
    typeof TraceparentParameter,
    typeof IfRightsVersionParameter,
  ];
  access: IdentifiedAccess<typeof operator, false>;
  requestBody: JsonRequestBody<
    z.ZodObject<
      {
        outcome: VocabularyIn<typeof DATE_OUTCOMES>;
        message: z.ZodObject<{ contentLanguage: z.ZodString; text: z.ZodString }, z.core.$strip>;
        rescheduledTo: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        expectedVersion: z.ZodInt;
      },
      z.core.$strip
    >
  >;
  responses: {
    200: JsonResponse<
      z.ZodIntersection<
        typeof StudioEnvelopeMetaSchema,
        z.ZodObject<
          {
            data: z.ZodObject<
              {
                outcome: z.ZodOptional<z.ZodString>;
                declaredAt: z.ZodOptional<z.ZodString>;
                moneyEffectCode: z.ZodOptional<z.ZodString>;
                affectedSeats: z.ZodOptional<z.ZodInt>;
              },
              z.core.$loose
            >;
          },
          z.core.$loose
        >
      >
    >;
    403: JsonResponse<typeof StudioErrorEnvelopeSchema>;
    409: typeof ConflictResponse;
  };
}> = date.action('outcome', {
  operationId: 'decideDateOutcome',
  summary: "Declares a date's outcome — postpone, cancel, interrupt.",
  description:
    "**Reserved to the owner and to production.** The other roles can only **report**. An outcome\ndecision is worth several thousand euros, and the log names names.\n\n**One event, four consequences, and none of the four consumers talks to the others**:\n`ticketing` refunds (cancelled) / credits (interrupted) / **does not move** (postponed — the\nseat follows the new date); `payouts` withholds; `catalog` replaces the state **on every\ncard**, not only on the record; `notifications` warns the holders.\n\n**A declared outcome is a fact: never rewritten, never erased.**\n\nThe control room's message travels **with its authoring language**: it is content, not an i18n\nkey.\n",
  'x-arthome-maturity': 'stable',
  'x-arthome-upstream': [Service.CATALOG],
  body: z.object({
    outcome: vocabularyIn(DATE_OUTCOMES).meta({
      'x-arthome-vocabulary-source': 'DATE_OUTCOMES',
    }),
    message: z.object({
      contentLanguage: z.string(),
      text: z.string().max(600),
    }),
    rescheduledTo: z
      .string()
      .regex(new RegExp('^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,3})?Z$'))
      .nullable()
      .meta({
        format: 'date-time',
        description: '**Required, and only permitted,** for `postponed`.',
      })
      .optional(),
    expectedVersion: z.int().meta({ minimum: undefined, maximum: undefined }),
  }),
  example: {
    outcome: DateOutcome.POSTPONED,
    message: {
      contentLanguage: Locale.FR,
      text: 'Report au 4 novembre. Vos places restent valables.',
    },
    rescheduledTo: '2026-11-04T19:30:00Z',
    expectedVersion: 8,
  },
  responses: {
    200: {
      description: 'Outcome declared, and what it implies for the holders.',
      content: {
        'application/json': {
          schema: z.intersection(
            StudioEnvelopeMetaSchema,
            z.looseObject({
              data: z.looseObject({
                outcome: z.string().optional(),
                declaredAt: InstantOut.optional(),
                moneyEffectCode: z
                  .string()
                  .meta({
                    description:
                      '`full_refund` · `account_credit` · `no_movement`. A **code**, never a sentence.',
                  })
                  .optional(),
                affectedSeats: z.int().meta({ minimum: undefined, maximum: undefined }).optional(),
              }),
            }),
          ),
          example: {
            servedAt: '2026-09-21T20:50:00.000Z',
            rightsVersion: 412,
            data: {
              outcome: DateOutcome.POSTPONED,
              declaredAt: '2026-09-21T20:50:00Z',
              moneyEffectCode: 'no_movement',
              affectedSeats: 174,
            },
          },
        },
      },
    },
    403: {
      description: '`date.outcome_decision_forbidden` — this role can only report.',
      content: {
        'application/json': {
          schema: StudioErrorEnvelopeSchema,
          example: {
            error: {
              code: CatalogErrorCode.OUTCOME_DECISION_FORBIDDEN,
              nature: FailureNature.REFUSED,
              params: {
                canEscalateTo: [MemberRole.ARTIST, MemberRole.PRODUCTION],
              },
              traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
            },
            servedAt: '2026-09-21T20:50:00.000Z',
          },
        },
      },
    },
    409: ConflictResponse,
  },
});
