import { z } from 'zod';

import { ApiErrorCode, ChatErrorCode, OrderErrorCode, Surface } from '@arthome/core';
import type { ErrorCode } from '@arthome/core';
import type { VocabularyIn } from '@arthome/core/schema';
import {
  ERROR_PARAMS,
  errorParamsSchemaOf,
  InstantOut,
  int64,
  VOCABULARY_SOURCE_LOCAL,
  vocabularyIn,
  uuidIn,
} from '@arthome/core/schema';

import {
  StorefrontEnvelopeMetaSchema,
  StorefrontErrorEnvelopeSchema,
  StorefrontErrorSchema,
} from '../envelope/index.js';
import type { StorefrontRelayedCode } from '../envelope/index.js';
import type {
  AccessorOf,
  CachePolicy,
  ErrorBody,
  ErrorModel,
  Freshness,
  Header,
  Identity,
  Paging,
  HeaderParameter,
  JsonResponse,
  PathParameter,
  QueryParameter,
  Response,
  ResourceConventions,
  RouteBuilder,
  SecurityRequirement,
  CodedResponse,
} from '../http/index.js';
import {
  accessorOf,
  cache,
  cursor,
  defineErrorModel,
  errorResponse,
  identity,
  routeBuilder,
} from '../http/index.js';
import { StorefrontCursorPageInfoSchema } from '../pagination/index.js';

const SURFACE: readonly [
  typeof Surface.STOREFRONT_WEB,
  typeof Surface.STOREFRONT_MOBILE,
  typeof Surface.STOREFRONT_TV,
] = [Surface.STOREFRONT_WEB, Surface.STOREFRONT_MOBILE, Surface.STOREFRONT_TV];
const CURSOR_DIRECTION = ['forward', 'backward'] as const;

const STOREFRONT_TAGS = [
  'bootstrap',
  'discovery',
  'date',
  'commerce',
  'playback',
  'chat',
  'pairing',
  'account',
] as const;

/**
 * **Public read.** A complete absence of authentication is a NOMINAL case, not an error: this
 * read is the indexable face of the product, and a search engine's crawler has neither cookie,
 * nor bearer token, nor any way of minting one. Guest mode takes the same path. See "Public read
 * and identified read" at the top of the document.
 */
export const PublicReadSecurity: readonly SecurityRequirement[] = [
  {},
  { sessionCookie: [] },
  { bearerToken: [] },
  { deviceToken: [] },
];

/** The tags this document groups its operations by. */
export const StorefrontTag: AccessorOf<typeof STOREFRONT_TAGS> = accessorOf(STOREFRONT_TAGS);

export const TraceparentParameter: HeaderParameter<'traceparent', z.ZodString> = {
  name: 'traceparent',
  in: 'header',
  required: false,
  description:
    'W3C trace context. Created by the surface when it can, otherwise by the BFF. It is\npropagated to the service and injected into `outbox_event.tracecontext` **at write time**:\ninjected later, the link is definitively lost.\n',
  schema: z
    .string()
    .regex(new RegExp('^[0-9a-f]{2}-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$'))
    .meta({
      examples: ['00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01'],
    }),
};

export const SurfaceParameter: HeaderParameter<
  'X-Arthome-Surface',
  VocabularyIn<typeof SURFACE>,
  true
> = {
  name: 'X-Arthome-Surface',
  in: 'header',
  required: true,
  description:
    'The calling surface. It determines three **served** things, never guessed: the chat rate\nceiling (television 2 msg/s, mobile 6, web 10), the size of the catch-up on entering a room\n(television 20 messages, 50 elsewhere) and which slice of the label and taxonomy catalogue to\nload.\n**A strict narrowing of `SURFACES`, and the strictness is the point.** The domain\nvocabulary has six members; this header accepts the three that can legitimately call the\nstorefront BFF and **refuses the rest**, because an input is refused where an output is kept\nraw and treated as neutral. A studio surface reaching this header is not a value to tolerate,\nit is a caller in the wrong place.\n',
  schema: vocabularyIn(SURFACE).meta({
    'x-arthome-vocabulary-source': 'SURFACES',
    'x-arthome-vocabulary-narrowing':
      'The three that may call the storefront BFF. A studio surface reaching this header is not a value to tolerate, it is a caller in the wrong place.',
    examples: [Surface.STOREFRONT_TV],
  }),
};

export const ViewerTimezoneParameter: HeaderParameter<'X-Arthome-Timezone', z.ZodString> = {
  name: 'X-Arthome-Timezone',
  in: 'header',
  required: false,
  description:
    "The viewer's IANA timezone, when the surface knows it. The server groups tonight's grid **in\nthe viewer's local time**: the grouping depends on the timezone, and Next's server rendering\ndoes not know the visitor's.\n",
  schema: z.string().meta({
    examples: ['Europe/Paris'],
  }),
};

export const IdempotencyKeyParameter: HeaderParameter<'Idempotency-Key', z.ZodString, true> = {
  name: 'Idempotency-Key',
  in: 'header',
  required: true,
  description:
    'UUIDv7 **generated by the surface before sending and persisted before sending**. A replayed\nkey returns the original response, verbatim, with `Idempotency-Replayed: true` — never a\nduplicate error. Lifetime **24 h**, which covers an offline queue replayed after a night.\nSee `architecture/transport.md` §5.4.\n',
  schema: uuidIn().meta({
    examples: ['019928f4-1b6c-7c3a-9f2e-6a1d0c4b8e77'],
  }),
};

export const AdmissionTokenParameter: HeaderParameter<'X-Arthome-Admission-Token', z.ZodString> = {
  name: 'X-Arthome-Admission-Token',
  in: 'header',
  required: false,
  description:
    "The admission out of a date's sales queue, as `getSalesQueuePosition` serves it: opaque to the\nsurface, bound to one account and one date, and valid until its `expiresAt`. Required on\n`purchaseSeat`, and on `createPairing` for a `seat` (D-086), while that date's queue is armed;\nignored otherwise. Provisional with the queue (D-081).\n",
  schema: z.string().min(1),
};

export const LateEntryAcknowledgedParameter: HeaderParameter<
  'X-Arthome-Late-Entry-Acknowledged',
  z.ZodLiteral<'true'>
> = {
  name: 'X-Arthome-Late-Entry-Acknowledged',
  in: 'header',
  required: false,
  description:
    '**Required once the live has started** (D-089): the buyer was told what they missed, as\n`SeatQuote.lateEntry` says it. Without it the purchase is refused with `409`\n`order.late_entry_unacknowledged` before any seat is held; any value but `true` is `400`.\nIgnored before the start. In a header, like the admission, so the idempotency fingerprint\nnever covers it: a purchase placed before the start and retried after it adds it under the\nsame key. A replayed key answers its original response without it.\n',
  schema: z.literal('true'),
};

export const CursorParameter: QueryParameter<'cursor', z.ZodString> = {
  name: 'cursor',
  in: 'query',
  required: false,
  description:
    '**Opaque** cursor, Base64-encoded over `(created_at, id)`. Bidirectional and **independent of\npage size**: changing `limit` between two calls does not invalidate it, which is exactly what\na screen rotation produces. Valid 24 h.\n',
  schema: z.string().meta({
    examples: ['eyJjIjoiMjAyNi0wOS0yMVQyMDowMDowMFoiLCJpIjoiMDE5OTI4ZjQifQ'],
  }),
};

export const CursorDirectionParameter: QueryParameter<
  'direction',
  z.ZodDefault<VocabularyIn<typeof CURSOR_DIRECTION>>
> = {
  name: 'direction',
  in: 'query',
  required: false,
  description: 'Direction of travel. `backward` moves towards the most recent.',
  schema: vocabularyIn(CURSOR_DIRECTION)
    .meta({
      'x-arthome-vocabulary-source': VOCABULARY_SOURCE_LOCAL,
      'x-arthome-vocabulary-reason':
        "A sort or filter key. It is a property of THIS endpoint's list — which orders it offers — not of the domain, and adding one is an endpoint change rather than a vocabulary change.",
    })
    .default('forward'),
};

export const LimitParameter: QueryParameter<'limit', z.ZodDefault<z.ZodInt>> = {
  name: 'limit',
  in: 'query',
  required: false,
  description:
    'Requested page size. Display density (`tiles` / `list` on mobile) varies it; the cursor\nsurvives that.\n',
  schema: z.int().min(1).max(50).default(20),
};

export const DateIdParameter: PathParameter<'dateId', z.ZodString> = {
  name: 'dateId',
  in: 'path',
  required: true,
  schema: uuidIn().meta({
    examples: ['019928a0-7d31-7a10-b8c4-2f9e11a4c001'],
  }),
};

export const ArtistIdParameter: PathParameter<'artistId', z.ZodString> = {
  name: 'artistId',
  in: 'path',
  required: true,
  schema: uuidIn(),
};

export const CategoryIdParameter: PathParameter<'categoryId', z.ZodString> = {
  name: 'categoryId',
  in: 'path',
  required: true,
  description: '**Stable** discipline identifier, never an array index.',
  schema: z.string().meta({
    examples: ['dance-contemporary'],
  }),
};

export const ServedAtHeader: Header = {
  description:
    "Server instant **of this response**. On a response replayed by idempotency, it differs from\nthe body's `servedAt`, which is the first attempt's: a replay proves an effect took place, it\ndoes not promise fresh data.\n",
  schema: InstantOut,
};

export const IdempotencyReplayedHeader: Header = {
  description: 'Present and `true` when the body is the memorised response of an earlier attempt.',
  schema: z.boolean(),
};

export const RetryAfterMsHeader: Header = {
  description:
    'Wait before retrying, in milliseconds. Used to disable a control cleanly rather than stack up refusals.',
  schema: z.int().min(0).meta({ maximum: undefined }),
};

export const CacheControlPublicHeader: Header = {
  description:
    "Set by the BFF. **`public` only on an anonymous read** — the body is then identical for every\ncaller, hence shareable in a common cache and in Next's render cache. As soon as a session or\na bearer token accompanies the request, the body carries the per-viewer overlays and the\nheader becomes `private`: **serving a personalised body as `public` would be a leak, not an\noptimisation.**\n",
  schema: z.string().meta({
    examples: ['public, max-age=60'],
  }),
};

const PUBLIC_READ_VARY: readonly string[] = [
  'Cookie',
  'Authorization',
  'X-Arthome-Device-Token',
  'X-Arthome-Surface',
];

/** The freshness of a public read: `public` for an anonymous caller, varying on every credential and the surface. */
export function publicRead(freshness: Freshness): CachePolicy {
  return cache(freshness, { scope: 'public', vary: PUBLIC_READ_VARY });
}

export const VaryAuthHeader: Header = {
  description:
    "**`Cookie, Authorization, X-Arthome-Device-Token, X-Arthome-Surface`.** Without this `Vary`,\nan intermediate cache would serve an anonymous visitor someone else's personalised body. The\nfirst three separate public from identified; `X-Arthome-Surface` separates the chat ceilings\nand the label catalogue slices, which differ per surface.\n",
  schema: z.string(),
};

/** `api.schema_invalid`'s envelope, so the document says what a refused field carries. */
const SchemaInvalidEnvelopeSchema: z.ZodType<ErrorBody<typeof ApiErrorCode.SCHEMA_INVALID>> =
  StorefrontErrorEnvelopeSchema.extend({
    error: StorefrontErrorSchema.extend({
      code: z.literal(ApiErrorCode.SCHEMA_INVALID),
      params: ERROR_PARAMS[ApiErrorCode.SCHEMA_INVALID],
    }),
  });

export const BadRequestResponse: JsonResponse<typeof SchemaInvalidEnvelopeSchema> &
  CodedResponse<typeof ApiErrorCode.SCHEMA_INVALID> = errorResponse(SchemaInvalidEnvelopeSchema, {
  description: 'Malformed request, or refused by shape validation.',
  code: ApiErrorCode.SCHEMA_INVALID,
});

export const UnauthorizedResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof ApiErrorCode.UNAUTHENTICATED> = errorResponse(
  StorefrontErrorEnvelopeSchema,
  {
    description: 'No valid session, or expired token.',
    code: ApiErrorCode.UNAUTHENTICATED,
  },
);

export const CsrfRefusedResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof ApiErrorCode.FORBIDDEN> = errorResponse(StorefrontErrorEnvelopeSchema, {
  description:
    "A write with the session cookie came without its `X-Arthome-Csrf` token, or with another\nsession's (`api.forbidden`). A write with a bearer token never meets it.\n",
  code: ApiErrorCode.FORBIDDEN,
});

export const ForbiddenResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof ApiErrorCode.FORBIDDEN> = errorResponse(StorefrontErrorEnvelopeSchema, {
  description: 'Session valide, droit absent.',
  code: ApiErrorCode.FORBIDDEN,
});

export const NotFoundResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof ApiErrorCode.NOT_FOUND> = errorResponse(StorefrontErrorEnvelopeSchema, {
  description: 'Ressource inconnue.',
  code: ApiErrorCode.NOT_FOUND,
});

export const ConflictResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof OrderErrorCode.PRICE_STALE> = errorResponse(StorefrontErrorEnvelopeSchema, {
  description:
    'Definitive business refusal. The `code` says which one, and `params` carries what the screen\nmust display — never a sentence.\n',
  code: OrderErrorCode.PRICE_STALE,
});

export const GoneResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof ApiErrorCode.CURSOR_TOO_OLD> = errorResponse(StorefrontErrorEnvelopeSchema, {
  description: 'The targeted cursor, pairing or replay has expired.',
  code: ApiErrorCode.CURSOR_TOO_OLD,
});

export const TooManyRequestsResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof ChatErrorCode.RATE_LIMITED> = errorResponse(StorefrontErrorEnvelopeSchema, {
  description:
    'Rate limit reached. `params.retryAfterMs` allows the control to be disabled instead of stacking up refusals.',
  headers: {
    'Retry-After-Ms': RetryAfterMsHeader,
  },
  code: ChatErrorCode.RATE_LIMITED,
});

export const UnavailableResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof ApiErrorCode.SERVICE_UNAVAILABLE> = errorResponse(
  StorefrontErrorEnvelopeSchema,
  {
    description:
      'Our servers. `nature: "unavailable"` is what lets the surface say "our servers" rather than\n"your connection" — a transport failure, by contrast, has no body and reads as "your\nconnection".\n',
    code: ApiErrorCode.SERVICE_UNAVAILABLE,
  },
);

export const PayloadTooLargeResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof ApiErrorCode.PAYLOAD_TOO_LARGE> = errorResponse(
  StorefrontErrorEnvelopeSchema,
  {
    description:
      'The body is over the ceiling of the route (1 MiB unless the route says otherwise).',
    code: ApiErrorCode.PAYLOAD_TOO_LARGE,
  },
);

export const UnsupportedMediaTypeResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof ApiErrorCode.UNSUPPORTED_MEDIA_TYPE> = errorResponse(
  StorefrontErrorEnvelopeSchema,
  {
    description: 'The body is not `application/json`.',
    code: ApiErrorCode.UNSUPPORTED_MEDIA_TYPE,
  },
);

export const InternalErrorResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof ApiErrorCode.INTERNAL> = errorResponse(StorefrontErrorEnvelopeSchema, {
  description: 'A fault of ours, never retried as is.',
  code: ApiErrorCode.INTERNAL,
});

export const BadGatewayResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof ApiErrorCode.UPSTREAM_UNAVAILABLE> = errorResponse(
  StorefrontErrorEnvelopeSchema,
  {
    description: 'A service behind the BFF failed.',
    code: ApiErrorCode.UPSTREAM_UNAVAILABLE,
  },
);

export const GatewayTimeoutResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> &
  CodedResponse<typeof ApiErrorCode.UPSTREAM_TIMEOUT> = errorResponse(
  StorefrontErrorEnvelopeSchema,
  {
    description:
      'The BFF stopped waiting for a service, or the deadline was already past. A command is retried with its `Idempotency-Key`.',
    code: ApiErrorCode.UPSTREAM_TIMEOUT,
  },
);

const IfNoneMatchParameter: HeaderParameter<'If-None-Match', z.ZodString> = {
  name: 'If-None-Match',
  in: 'header',
  required: false,
  schema: z.string(),
};

const ETagHeader: Header = {
  description:
    "The record's validator: send it back in `If-None-Match` to learn that nothing changed.",
  schema: z.string(),
};

const OWN_LIST_PARAMETERS: readonly [typeof CursorParameter, typeof LimitParameter] = [
  CursorParameter,
  LimitParameter,
];

/** What every storefront resource is served and written like: see `ResourceConventions`. */
export const storefrontConventions: {
  readonly meta?: z.output<typeof StorefrontEnvelopeMetaSchema>;
  readonly item: ResourceConventions['item'];
  readonly page: ResourceConventions['page'];
  readonly listParameters: typeof OWN_LIST_PARAMETERS;
  readonly readParameters: readonly [typeof IfNoneMatchParameter];
  readonly readHeaders: { readonly ETag: Header };
  readonly notModified: Response;
  readonly writeParameters: readonly [typeof IdempotencyKeyParameter];
  readonly replayedHeader: Header;
  readonly itemExample: (data: unknown) => unknown;
  readonly pageExample: (data: readonly unknown[]) => unknown;
  readonly expectedVersion: z.ZodNumber;
  readonly paging: Paging;
  readonly paginations: {
    readonly cursor: {
      readonly parameters: (paging: {
        readonly maxLimit: number;
      }) => readonly [typeof CursorParameter, QueryParameter<'limit', z.ZodDefault<z.ZodInt>>];
      readonly page: ResourceConventions['page'];
    };
  };
} = {
  item: (data) => z.intersection(StorefrontEnvelopeMetaSchema, z.looseObject({ data })),
  page: (data) =>
    z.intersection(
      StorefrontEnvelopeMetaSchema,
      z.looseObject({ items: z.array(data), page: StorefrontCursorPageInfoSchema }),
    ),
  listParameters: OWN_LIST_PARAMETERS,
  readParameters: [IfNoneMatchParameter],
  readHeaders: { ETag: ETagHeader },
  notModified: { description: 'Unchanged since the validator sent in `If-None-Match`.' },
  writeParameters: [IdempotencyKeyParameter],
  replayedHeader: IdempotencyReplayedHeader,
  itemExample: (data) => ({ servedAt: '2026-09-21T19:00:00.000Z', data }),
  pageExample: (items) => ({
    servedAt: '2026-09-21T19:00:00.000Z',
    items,
    page: { hasMore: false },
  }),
  expectedVersion: int64(),
  paging: cursor({ maxLimit: 50 }),
  paginations: {
    cursor: {
      parameters: (paging) => [
        CursorParameter,
        paging.maxLimit === 50
          ? LimitParameter
          : {
              name: 'limit',
              in: 'query',
              required: false,
              schema: z.int().min(1).max(paging.maxLimit).default(20),
            },
      ],
      page: (data) =>
        z.intersection(
          StorefrontEnvelopeMetaSchema,
          z.looseObject({ items: z.array(data), page: StorefrontCursorPageInfoSchema }),
        ),
    },
  },
};

/**
 * The codes a storefront response stands for. A 409 is the business refusal whose `code` says
 * which, so it already covers the idempotency refusals.
 */
export const storefrontErrors: ErrorModel<StorefrontRelayedCode> = defineErrorModel({
  standard: {
    400: { response: BadRequestResponse, codes: [ApiErrorCode.SCHEMA_INVALID] },
    401: { response: UnauthorizedResponse, codes: [ApiErrorCode.UNAUTHENTICATED] },
    403: { response: ForbiddenResponse, codes: [ApiErrorCode.FORBIDDEN] },
    404: { response: NotFoundResponse, codes: [ApiErrorCode.NOT_FOUND] },
    409: {
      response: ConflictResponse,
      codes: [ApiErrorCode.IDEMPOTENCY_KEY_REUSED, ApiErrorCode.IDEMPOTENCY_IN_FLIGHT],
    },
    410: { response: GoneResponse, codes: [ApiErrorCode.CURSOR_TOO_OLD] },
    429: { response: TooManyRequestsResponse, codes: [ApiErrorCode.RATE_LIMITED] },
    413: { response: PayloadTooLargeResponse, codes: [ApiErrorCode.PAYLOAD_TOO_LARGE] },
    415: {
      response: UnsupportedMediaTypeResponse,
      codes: [ApiErrorCode.UNSUPPORTED_MEDIA_TYPE],
    },
    500: { response: InternalErrorResponse, codes: [ApiErrorCode.INTERNAL] },
    502: { response: BadGatewayResponse, codes: [ApiErrorCode.UPSTREAM_UNAVAILABLE] },
    503: { response: UnavailableResponse, codes: [ApiErrorCode.SERVICE_UNAVAILABLE] },
    504: {
      response: GatewayTimeoutResponse,
      codes: [ApiErrorCode.UPSTREAM_TIMEOUT, ApiErrorCode.DEADLINE_EXCEEDED],
    },
  },
  upstreams: true,
  envelopeOf: (code) =>
    StorefrontErrorEnvelopeSchema.extend({
      error: StorefrontErrorSchema.extend({
        code: z.literal(code),
        params: errorParamsSchemaOf(code as ErrorCode),
      }),
    }),
});

export const ViewerPrincipalSchema: z.ZodObject<
  { accountId: z.ZodString; deviceId: z.ZodString },
  z.core.$strip
> = z.object({ accountId: z.string(), deviceId: z.string() });

export const DevicePrincipalSchema: z.ZodObject<{ deviceId: z.ZodString }, z.core.$strip> =
  z.object({ deviceId: z.string() });

/** A signed-in viewer, by session cookie (a write carries its CSRF token) or bearer token. */
export const viewer: Identity<
  'viewer',
  typeof ViewerPrincipalSchema,
  typeof ApiErrorCode.FORBIDDEN,
  readonly [],
  readonly []
> = identity('viewer', {
  schemes: {
    read: [{ sessionCookie: [] }, { bearerToken: [] }],
    write: [{ sessionCookie: [], csrfToken: [] }, { bearerToken: [] }],
  },
  principal: ViewerPrincipalSchema,
  optionalAlso: [{ deviceToken: [] }],
  writeErrors: [ApiErrorCode.FORBIDDEN],
  writeResponses: { 403: CsrfRefusedResponse },
});

/**
 * A signed-in viewer, or a device that holds only its device token: the bootstrap is read and a
 * pairing driven before any session. Either credential reads and writes, and the principal says
 * which one called.
 */
export const viewerOrDevice: Identity<
  'viewer_or_device',
  z.ZodUnion<readonly [typeof ViewerPrincipalSchema, typeof DevicePrincipalSchema]>,
  typeof ApiErrorCode.FORBIDDEN,
  readonly [],
  readonly []
> = identity('viewer_or_device', {
  schemes: {
    read: [{ sessionCookie: [] }, { bearerToken: [] }, { deviceToken: [] }],
    write: [{ sessionCookie: [], csrfToken: [] }, { bearerToken: [] }, { deviceToken: [] }],
  },
  principal: z.union([ViewerPrincipalSchema, DevicePrincipalSchema]),
  writeErrors: [ApiErrorCode.FORBIDDEN],
  writeResponses: { 403: CsrfRefusedResponse },
});

/** The television, paired to an account: it holds a device token and no session. */
export const device: Identity<
  'paired_device',
  typeof DevicePrincipalSchema,
  never,
  readonly [],
  readonly []
> = identity('paired_device', {
  schemes: { read: [{ deviceToken: [] }], write: [{ deviceToken: [] }] },
  principal: DevicePrincipalSchema,
});

export const storefrontV1: RouteBuilder<
  1,
  readonly [],
  Record<never, never>,
  StorefrontRelayedCode,
  typeof storefrontConventions
> = routeBuilder(storefrontErrors).version(1).conventions(storefrontConventions);
