import { z } from 'zod';

import {
  ApiErrorCode,
  ChatErrorCode,
  FailureNature,
  OrderErrorCode,
  Service,
  Surface,
} from '@arthome/core';
import type { VocabularyIn } from '@arthome/core/schema';
import { InstantOut, uuidOut, VOCABULARY_SOURCE_LOCAL, vocabularyIn } from '@arthome/core/schema';

import { StorefrontErrorEnvelopeSchema } from '../envelope/index.js';
import type {
  AccessorOf,
  Header,
  HeaderParameter,
  JsonResponse,
  PathParameter,
  QueryParameter,
  SecurityRequirement,
} from '../http/index.js';
import { accessorOf } from '../http/index.js';

const SURFACE: readonly [
  typeof Surface.STOREFRONT_WEB,
  typeof Surface.STOREFRONT_MOBILE,
  typeof Surface.STOREFRONT_TV,
] = [Surface.STOREFRONT_WEB, Surface.STOREFRONT_MOBILE, Surface.STOREFRONT_TV];
const CURSOR_DIRECTION = ['forward', 'backward'] as const;

const STOREFRONT_TAGS = [
  'bootstrap',
  'discovery',
  'date',
  'commerce',
  'playback',
  'chat',
  'pairing',
  'account',
] as const;

/**
 * **Public read.** A complete absence of authentication is a NOMINAL case, not an error: this
 * read is the indexable face of the product, and a search engine's crawler has neither cookie,
 * nor bearer token, nor any way of minting one. Guest mode takes the same path. See "Public read
 * and identified read" at the top of the document.
 */
export const PublicReadSecurity: readonly SecurityRequirement[] = [
  {},
  { sessionCookie: [] },
  { bearerToken: [] },
  { deviceToken: [] },
];

/** The tags this document groups its operations by. */
export const StorefrontTag: AccessorOf<typeof STOREFRONT_TAGS> = accessorOf(STOREFRONT_TAGS);

export const TraceparentParameter: HeaderParameter<'traceparent', z.ZodString> = {
  name: 'traceparent',
  in: 'header',
  required: false,
  description:
    'W3C trace context. Created by the surface when it can, otherwise by the BFF. It is\npropagated to the service and injected into `outbox_event.tracecontext` **at write time**:\ninjected later, the link is definitively lost.\n',
  schema: z
    .string()
    .regex(new RegExp('^[0-9a-f]{2}-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$'))
    .meta({
      examples: ['00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01'],
    }),
};

export const SurfaceParameter: HeaderParameter<
  'X-Arthome-Surface',
  VocabularyIn<typeof SURFACE>,
  true
> = {
  name: 'X-Arthome-Surface',
  in: 'header',
  required: true,
  description:
    'The calling surface. It determines three **served** things, never guessed: the chat rate\nceiling (television 2 msg/s, mobile 6, web 10), the size of the catch-up on entering a room\n(television 20 messages, 50 elsewhere) and which slice of the label and taxonomy catalogue to\nload.\n**A strict narrowing of `SURFACES`, and the strictness is the point.** The domain\nvocabulary has six members; this header accepts the three that can legitimately call the\nstorefront BFF and **refuses the rest**, because an input is refused where an output is kept\nraw and treated as neutral. A studio surface reaching this header is not a value to tolerate,\nit is a caller in the wrong place.\n',
  schema: vocabularyIn(SURFACE).meta({
    'x-arthome-vocabulary-source': 'SURFACES',
    'x-arthome-vocabulary-narrowing':
      'The three that may call the storefront BFF. A studio surface reaching this header is not a value to tolerate, it is a caller in the wrong place.',
    examples: [Surface.STOREFRONT_TV],
  }),
};

export const ViewerTimezoneParameter: HeaderParameter<'X-Arthome-Timezone', z.ZodString> = {
  name: 'X-Arthome-Timezone',
  in: 'header',
  required: false,
  description:
    "The viewer's IANA timezone, when the surface knows it. The server groups tonight's grid **in\nthe viewer's local time**: the grouping depends on the timezone, and Next's server rendering\ndoes not know the visitor's.\n",
  schema: z.string().meta({
    examples: ['Europe/Paris'],
  }),
};

export const IdempotencyKeyParameter: HeaderParameter<'Idempotency-Key', z.ZodString, true> = {
  name: 'Idempotency-Key',
  in: 'header',
  required: true,
  description:
    'UUIDv7 **generated by the surface before sending and persisted before sending**. A replayed\nkey returns the original response, verbatim, with `Idempotency-Replayed: true` — never a\nduplicate error. Lifetime **24 h**, which covers an offline queue replayed after a night.\nSee `architecture/transport.md` §5.4.\n',
  schema: uuidOut().meta({
    examples: ['019928f4-1b6c-7c3a-9f2e-6a1d0c4b8e77'],
  }),
};

export const AdmissionTokenParameter: HeaderParameter<'X-Arthome-Admission-Token', z.ZodString> = {
  name: 'X-Arthome-Admission-Token',
  in: 'header',
  required: false,
  description:
    "The admission out of a date's sales queue, as `getSalesQueuePosition` serves it: opaque to the\nsurface, bound to one account and one date, and valid until its `expiresAt`. Required on\n`purchaseSeat`, and on `createPairing` for a `seat` (D-086), while that date's queue is armed;\nignored otherwise. Provisional with the queue (D-081).\n",
  schema: z.string().min(1),
};

export const LateEntryAcknowledgedParameter: HeaderParameter<
  'X-Arthome-Late-Entry-Acknowledged',
  z.ZodLiteral<'true'>
> = {
  name: 'X-Arthome-Late-Entry-Acknowledged',
  in: 'header',
  required: false,
  description:
    '**Required once the live has started** (D-089): the buyer was told what they missed, as\n`SeatQuote.lateEntry` says it. Without it the purchase is refused with `409`\n`order.late_entry_unacknowledged` before any seat is held; any value but `true` is `400`.\nIgnored before the start. In a header, like the admission, so the idempotency fingerprint\nnever covers it: a purchase placed before the start and retried after it adds it under the\nsame key. A replayed key answers its original response without it.\n',
  schema: z.literal('true'),
};

export const CursorParameter: QueryParameter<'cursor', z.ZodString> = {
  name: 'cursor',
  in: 'query',
  required: false,
  description:
    '**Opaque** cursor, Base64-encoded over `(created_at, id)`. Bidirectional and **independent of\npage size**: changing `limit` between two calls does not invalidate it, which is exactly what\na screen rotation produces. Valid 24 h.\n',
  schema: z.string().meta({
    examples: ['eyJjIjoiMjAyNi0wOS0yMVQyMDowMDowMFoiLCJpIjoiMDE5OTI4ZjQifQ'],
  }),
};

export const CursorDirectionParameter: QueryParameter<
  'direction',
  z.ZodDefault<VocabularyIn<typeof CURSOR_DIRECTION>>
> = {
  name: 'direction',
  in: 'query',
  required: false,
  description: 'Direction of travel. `backward` moves towards the most recent.',
  schema: vocabularyIn(CURSOR_DIRECTION)
    .meta({
      'x-arthome-vocabulary-source': VOCABULARY_SOURCE_LOCAL,
      'x-arthome-vocabulary-reason':
        "A sort or filter key. It is a property of THIS endpoint's list — which orders it offers — not of the domain, and adding one is an endpoint change rather than a vocabulary change.",
    })
    .default('forward'),
};

export const LimitParameter: QueryParameter<'limit', z.ZodDefault<z.ZodInt>> = {
  name: 'limit',
  in: 'query',
  required: false,
  description:
    'Requested page size. Display density (`tiles` / `list` on mobile) varies it; the cursor\nsurvives that.\n',
  schema: z.int().min(1).max(50).default(20),
};

export const DateIdParameter: PathParameter<'dateId', z.ZodString> = {
  name: 'dateId',
  in: 'path',
  required: true,
  schema: uuidOut().meta({
    examples: ['019928a0-7d31-7a10-b8c4-2f9e11a4c001'],
  }),
};

export const ArtistIdParameter: PathParameter<'artistId', z.ZodString> = {
  name: 'artistId',
  in: 'path',
  required: true,
  schema: uuidOut(),
};

export const CategoryIdParameter: PathParameter<'categoryId', z.ZodString> = {
  name: 'categoryId',
  in: 'path',
  required: true,
  description: '**Stable** discipline identifier, never an array index.',
  schema: z.string().meta({
    examples: ['dance-contemporary'],
  }),
};

export const ServedAtHeader: Header = {
  description:
    "Server instant **of this response**. On a response replayed by idempotency, it differs from\nthe body's `servedAt`, which is the first attempt's: a replay proves an effect took place, it\ndoes not promise fresh data.\n",
  schema: InstantOut,
};

export const IdempotencyReplayedHeader: Header = {
  description: 'Present and `true` when the body is the memorised response of an earlier attempt.',
  schema: z.boolean(),
};

export const RetryAfterMsHeader: Header = {
  description:
    'Wait before retrying, in milliseconds. Used to disable a control cleanly rather than stack up refusals.',
  schema: z.int().min(0).meta({ maximum: undefined }),
};

export const CacheControlPublicHeader: Header = {
  description:
    "Set by the BFF. **`public` only on an anonymous read** — the body is then identical for every\ncaller, hence shareable in a common cache and in Next's render cache. As soon as a session or\na bearer token accompanies the request, the body carries the per-viewer overlays and the\nheader becomes `private`: **serving a personalised body as `public` would be a leak, not an\noptimisation.**\n",
  schema: z.string().meta({
    examples: ['public, max-age=60'],
  }),
};

export const VaryAuthHeader: Header = {
  description:
    "**`Cookie, Authorization, X-Arthome-Device-Token, X-Arthome-Surface`.** Without this `Vary`,\nan intermediate cache would serve an anonymous visitor someone else's personalised body. The\nfirst three separate public from identified; `X-Arthome-Surface` separates the chat ceilings\nand the label catalogue slices, which differ per surface.\n",
  schema: z.string(),
};

export const BadRequestResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> = {
  description: 'Malformed request, or refused by shape validation.',
  content: {
    'application/json': {
      schema: StorefrontErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.SCHEMA_INVALID,
          nature: FailureNature.REFUSED,
          params: {
            fields: ['tier'],
          },
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const UnauthorizedResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> = {
  description: 'No valid session, or expired token.',
  content: {
    'application/json': {
      schema: StorefrontErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.UNAUTHENTICATED,
          nature: FailureNature.REFUSED,
          params: {},
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const CsrfRefusedResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> = {
  description:
    "A write with the session cookie came without its `X-Arthome-Csrf` token, or with another\nsession's (`api.forbidden`). A write with a bearer token never meets it.\n",
  content: {
    'application/json': {
      schema: StorefrontErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.FORBIDDEN,
          nature: FailureNature.REFUSED,
          params: {},
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const ForbiddenResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> = {
  description: 'Session valide, droit absent.',
  content: {
    'application/json': {
      schema: StorefrontErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.FORBIDDEN,
          nature: FailureNature.REFUSED,
          params: {},
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const NotFoundResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> = {
  description: 'Ressource inconnue.',
  content: {
    'application/json': {
      schema: StorefrontErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.NOT_FOUND,
          nature: FailureNature.REFUSED,
          params: {},
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const ConflictResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> = {
  description:
    'Definitive business refusal. The `code` says which one, and `params` carries what the screen\nmust display — never a sentence.\n',
  content: {
    'application/json': {
      schema: StorefrontErrorEnvelopeSchema,
      example: {
        error: {
          code: OrderErrorCode.PRICE_STALE,
          nature: FailureNature.REFUSED,
          params: {
            expectedAmountMinor: 2400,
            currentAmountMinor: 2900,
            currencyCode: 'EUR',
          },
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const GoneResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> = {
  description: 'The targeted cursor, pairing or replay has expired.',
  content: {
    'application/json': {
      schema: StorefrontErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.CURSOR_TOO_OLD,
          nature: FailureNature.REFUSED,
          params: {
            maxAgeHours: 24,
          },
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const TooManyRequestsResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> = {
  description:
    'Rate limit reached. `params.retryAfterMs` allows the control to be disabled instead of stacking up refusals.',
  headers: {
    'Retry-After-Ms': RetryAfterMsHeader,
  },
  content: {
    'application/json': {
      schema: StorefrontErrorEnvelopeSchema,
      example: {
        error: {
          code: ChatErrorCode.RATE_LIMITED,
          nature: FailureNature.UNAVAILABLE,
          params: {
            retryAfterMs: 3000,
          },
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};

export const UnavailableResponse: JsonResponse<typeof StorefrontErrorEnvelopeSchema> = {
  description:
    'Our servers. `nature: "unavailable"` is what lets the surface say "our servers" rather than\n"your connection" — a transport failure, by contrast, has no body and reads as "your\nconnection".\n',
  content: {
    'application/json': {
      schema: StorefrontErrorEnvelopeSchema,
      example: {
        error: {
          code: ApiErrorCode.UPSTREAM_UNAVAILABLE,
          nature: FailureNature.UNAVAILABLE,
          params: {
            service: Service.CATALOG,
          },
          traceId: '4bf92f3577b34da6a3ce929d0e0e4736',
        },
        servedAt: '2026-09-21T20:31:04.118Z',
      },
    },
  },
};
